// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj1Q3llqge3Jylg3dRdP4G7C9ZgsDEx5k',
    appId: '1:757447120021:android:9babfe5324b749dfc1f79c',
    messagingSenderId: '757447120021',
    projectId: 'nnportal-fb0dd',
    storageBucket: 'nnportal-fb0dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqqHGBZdXh0yKVtVNO0K9cthHPzuDTjsc',
    appId: '1:757447120021:ios:0cf758b4800d17e1c1f79c',
    messagingSenderId: '757447120021',
    projectId: 'nnportal-fb0dd',
    storageBucket: 'nnportal-fb0dd.appspot.com',
    androidClientId: '757447120021-4lp6j824bvf99orqd62dgclofu13bm0i.apps.googleusercontent.com',
    iosClientId: '757447120021-1mb1ifihfccci21bngm0vjkbkn3ostfd.apps.googleusercontent.com',
    iosBundleId: 'com.netsolutions.nnportal',
  );
}
